### ISSUE TITLE
Add icon to the iOS app (ipa file)

### ISSUE THREAD

**Issue by Dajen** [PokeMapMobile/PokeMapMobile#1]
Could it be possible to add any suitable icon to the iOS app ipa file? Because the app looks quite awfull on the phone without any icon :)

![icon](https://cloud.githubusercontent.com/assets/20979819/17608649/1b6138c0-602e-11e6-873e-ae27a4753ef6.jpg)

Thank you in advance!

**Comment by PokeMapMobile** [comment]
This and more coming in the next release! Weaving in dev time during the work week, will have something by the weekend 😄
